### ISSUE TITLE
Issue created by commit #0fa1e29

### ISSUE THREAD

**Issue by mkayoh** [mgeeky/ProtectMyTooling#10]
In the aforementioned commit you changed the structure of the configPath() in lib/utils.py. I believe this causes now the packers to malfunction as they are trying to use two variables for this path, which produces the following error when running:
![image](https://user-images.githubusercontent.com/12525848/228841090-7467e1bf-099f-4813-8b53-16330c50a3a5.png)

**Comment by mgeeky** [comment]
Ah dang, what a shame! You're right, my Visual Code let me believing there are no more instances of `configPath` when I was looking for it across the files. I probably fell into believing machine instead of double-hand checking.

Thank you for letting me know, hopefully that's now addressed with latest commit.

Let me know if problem remains, otherwise - kindly close the issue :)

**Comment by mkayoh** [comment]
Yup, seems to be working now :)
